# Basic dependabot.yml file with

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Enable version updates for submodules
  - package-ecosystem: "gitsubmodules"
    directory: "/"
    schedule:
      interval: "daily"
