name: Changelog Update

on:
  pull_request:
    branches: [master]
    types: [synchronize, opened, reopened, ready_for_review]
    paths:
    - CHANGELOG.md
    ## make this dependabot friendly:
    - .gitsubmodules
    - workflows/**

jobs:
  update-check:
    name: Changelog has been updated
    runs-on: ubuntu-latest
    steps:
      - name: Success
        run: echo Success
    # no steps - always succeeds only has to be triggered
    # (-> enforces changes to CHANGELOG.md for every pull request)
