name: PullRequest

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  format-check:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - name: Check_clang-format_style
      uses: jidicula/clang-format-action@v4.11.0
      with: 
        clang-format-version: "16"
    

  build-and-test:
    if: github.event.pull_request.draft == false
    strategy:
      fail-fast: false
      matrix:
        name:
        - Linux-Docs
        - Linux-GNU
        - Linux-Clang
        - Linux-Clang-libc++
        - MacOS-Clang
        - Release-Test
        include:
        - name: Linux-Docs
          compiler: g++-9
          os: ubuntu-20.04
          dep-install: sudo apt-get update && sudo apt-get install -y cmake ninja-build texlive-latex-extra doxygen graphviz
          build_type: Debug
          binary-path: /build/src/Grazer/grazer
          specific-target: --target doxygen user_guide
          generator-command: -G"Ninja"
        - name: Linux-GNU
          compiler: g++-9
          os: ubuntu-20.04
          dep-install: sudo apt-get update && sudo apt-get install -y cmake ninja-build
          build_type: Debug
          binary-path: /build/src/Grazer/grazer
          generator-command: -G"Ninja"
        - name: Linux-Clang
          compiler: clang++-10
          os: ubuntu-20.04
          dep-install: sudo apt-get update && sudo apt-get install -y cmake clang ninja-build
          build_type: Debug
          binary-path: /build/src/Grazer/grazer
          generator-command: -G"Ninja"
        - name: Linux-Clang-libc++
          compiler: clang++-10
          os: ubuntu-20.04
          dep-install: sudo apt-get update && sudo apt-get install -y cmake clang libc++abi-10-dev  libc++-10-dev ninja-build
          build_type: Debug
          build_with_libcpp: ON
          binary-path: /build/src/Grazer/grazer
          generator-command: -G"Ninja"
        - name: MacOS-Clang
          os: macos-14
          compiler: clang++
          build_type: Debug
          binary-path: /build/src/Grazer/grazer
          dep-install: brew install bash metis ninja pkg-config; echo "/usr/local/bin" >> $GITHUB_PATH; echo "SDKROOT=$(xcrun --sdk macosx --show-sdk-path)" >> $GITHUB_ENV; echo "FC=gfortran-14" >> $GITHUB_ENV;
          generator-command: -G"Ninja"
        - name: Release-Test
          os: ubuntu-22.04
          compiler: clang++-15
          dep-install: sudo apt-get update && sudo apt-get install -y cmake ninja-build clang-15
          build_type: Release
          binary-path: /build/src/Grazer/grazer
          generator-command: -G"Ninja"

          

    env:
      CXX: ${{ matrix.compiler }}
      CTEST_OUTPUT_ON_FAILURE: 1
      BUILD_WITH_LIBCPP: ${{ matrix.build_with_libcpp }}
      # acts like a ternary:
      CCACHE_OPTIONS: ${{'-D CMAKE_CXX_COMPILER_LAUNCHER=ccache -D CMAKE_C_COMPILER_LAUNCHER=ccache'}}
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.os }} 

    steps:
    - name: Checkout_Repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Set_up_CCache
      uses: hendrikmuhs/ccache-action@v1 
      with:
        key: ${{ matrix.name }}


    - name: Install_Dependencies
      run: ${{ matrix.dep-install }}

    - name: Create_Build_Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure_CMake
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: bash
      working-directory: ${{github.workspace}}/build
      # Note the current convention is to use the -S and -B options here to specify source 
      # and build directories, but this is only available with CMake 3.13 and higher.  
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
      run: | 
        echo "Build with Libcpp: $BUILD_WITH_LIBCPP"
        cmake $GITHUB_WORKSPACE \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          $CCACHE_OPTIONS \
          -DBUILD_WITH_LIBCPP=${BUILD_WITH_LIBCPP} \
          ${{ matrix.generator-command }}

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config ${{ matrix.build_type }}  ${{ matrix.specific-target }}

    - name: Unit_Tests
      if: matrix.name != 'Linux-Docs'
      working-directory: ${{github.workspace}}/build
      shell: bash
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -V -C ${{ matrix.build_type }}
    
    - name: Integration_Test
      if: matrix.name != 'Linux-Docs'
      run: ${{github.workspace}}${{ matrix.binary-path }} run ./data/basetest && ${{github.workspace}}${{ matrix.binary-path }} run ./data/optimization_test
