on:
  release:
    types: [created]
name: Add Binaries to Release
jobs:
  generate:
    name: Create release-artifacts

    strategy:
      fail-fast: false
      matrix:
        name:
        - ubuntu-20.04
        - MacOS
        - Windows
        include:
        - name: MacOS
          os: macos-10.15
          compiler: clang++
        - name: Windows
          os: windows-2019
          compiler: msvs
        - name: ubuntu-20.04
          os: ubuntu-20.04
          compiler: g++-10
          dep-install: sudo apt-get install -y cmake doxygen graphviz

    env:
      # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
      CXX: ${{ matrix.compiler }}
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{matrix.os}}

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install Dependencies
      run: ${{ matrix.dep-install }}

    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: bash
      working-directory: ${{github.workspace}}/build
      # Note the current convention is to use the -S and -B options here to specify source 
      # and build directories, but this is only available with CMake 3.13 and higher.  
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
      run: cmake $GITHUB_WORKSPACE ${{ matrix.generator }} -DCMAKE_BUILD_TYPE=Release
    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config $BUILD_TYPE --parallel 10

    - name: Upload the artifacts
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: '${{github.workspace}}/build/src/Grazer/grazer*'
